### ISSUE TITLE
Re-brand

### ISSUE THREAD

**Issue by wolfbeast** [siggi90/NoobSilver#1]
You should give re-branding priority. Do not issue any releases before you've done this.

**Comment by siggi90** [comment]
Alright, i have no objections but what do you mean exactly? I've changed the logo and the config files that determine the browser name, is there something else that i should do in addition to that?

**Comment by siggi90** [comment]
Btw, I'm using the unofficial branding.

**Comment by wolfbeast** [comment]
That's fine; please just remove the official branding folder then. I'd like to keep my IP out of the distributed source :)

**Comment by siggi90** [comment]
Alright, done and done.
